### ISSUE TITLE
i can't load my save file

### ISSUE THREAD

**Issue by akrWkddl** [JulienNigon/SpellcasterUniversity-Bug-Report#1008]
i was playing campaign and at last stage, i saved and quited.
but when i tried to load my file. it does not loaded..
can you check for that..?

**Comment by akrWkddl** [comment]
![20200416022155_1](https://user-images.githubusercontent.com/16353255/79367623-22d73e00-7f89-11ea-958b-22f62dcf96a8.jpg)
it only shows this screen and does not progress

**Comment by Neelan22** [comment]
Can you send us your save file pls?
You can find it : 
PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves

Thank you !

**Comment by akrWkddl** [comment]
oh..i see this too late. sorry.
this is save file..!

[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/4498533/save.zip)

**Comment by Neelan22** [comment]
We are working on it, thank you !
Is it your first save? Have you other saves working?

Your file is corrupted, if you want to play your game you have to erase all the first line and put instead : 

![image](https://user-images.githubusercontent.com/47151033/79737775-1db51e80-82fc-11ea-8c9a-e4d89878fd87.png)

(sorry for this, I add to put a picture because the code was not displayed by github)

Does it solve your problem? It's a temporary solution
Here is your save : 
[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/4502593/save.zip)

**Comment by akrWkddl** [comment]
oh, it solved. thanks..!
and..I have tried twice more.. and there was same phenomenon..!

**Comment by Neelan22** [comment]
ok. 
Thanks to you, the problem should be solved with the last update we did. Your next saves should be ok. For the old ones, you have to do the correction I gave you.

**Comment by akrWkddl** [comment]
ok! thanks..!
