### ISSUE TITLE
Vampire sleep all the time 

### ISSUE THREAD

**Issue by Daboohumus** [JulienNigon/SpellcasterUniversity-Bug-Report#1118]
Hello !
My vampires are always tired. Their Bar don't change.

thanks

**Comment by DrAntonius** [comment]
I think it works as intended : vampires sleep all day long (that is, their bar is always full during the day so that they can only go to sleep) but never sleep at night. Therefore, they occupy a lot of room in the dormitory and the shadow classroom (where you probably sent them) should be as close to the dormitory as possible in order to save time.

**Comment by Neelan22** [comment]
DrAntonius is right. 
Vampires sleep all day long.
