### ISSUE TITLE
Belvedere Room

### ISSUE THREAD

**Issue by WraithBAD** [JulienNigon/SpellcasterUniversity-Bug-Report#605]
I am unable to put the Belvedere room down anywhere, have tried on more than one occasion on several maps.

**Comment by RADTrooper** [comment]
This one is not a bug I believe.  That room is a little confusing to place, but it is doable.    Each room has some combination of side doors and a staircase (door in the back of the room).  Side doors allow placement to the sides of your university while the staircases allow vertical placement.  The student recreation room you start with for example, only has a staircase which is why you cannot place it on first floor when first starting out.  When selecting a room card to place, if you highlight over the room and right click, it will show you the dimensions of the room and that specific room's combination of side doors/staircase.  

The Belvedere specifically, has no staircase, and only a single side door on the second floor right side.   Meaning to place the room, there must be an existing room on the second floor right side that has side door access.

**Comment by RADTrooper** [comment]
A couple of screenshots showing a possible placement.  
![1](https://user-images.githubusercontent.com/55932116/66360622-6b120580-e941-11e9-971b-a77411792b67.png)

![2](https://user-images.githubusercontent.com/55932116/66360627-706f5000-e941-11e9-8360-db762cd58c7a.png)
