### ISSUE TITLE
All young women are inspiring / Destabilizing

### ISSUE THREAD

**Issue by AvalonHillFan** [JulienNigon/SpellcasterUniversity-Bug-Report#637]
Don't do what E&Y did

https://www.huffpost.com/entry/women-ernst-young-how-to-dress-act-around-men_n_5da721eee4b002e33e78606a

**Comment by JulienNigon** [comment]
"Inspiring" is not about the physical or being a woman, just as another character is "punctual" or "friendly" for example. But **"Destabilizing" will be modified** as soon as the next patch is released. It is indeed a clumsy choice, and we will change it. Thank you.

**Comment by AvalonHillFan** [comment]
Quiet is not quite neutral . . . if _all_ women are quiet (weak?) and _no_ men are weak, that is also imperfect.

**Comment by JulienNigon** [comment]
I understand your point of view (although I think there is room for debate on "quiet"). But on the substance I agree completely. We kept it in reserve for time reasons (the team is very small), but the mirror versions for the other sex of the "young female teacher" and the "large male teacher" are planned from the initial prototype (we already have concept arts) and are being modelised. They will be integrated in the coming months. For early access we wanted as many male models as female models, and we had kept this structure because we really like the " large male teacher " model. But soon we will have models of both sexes.
